In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

c:\Users\omi222\Anaconda3\envs\project_lehigh\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x = torch.arange(-1, 1.1, 0.1)
t = torch.arange(0, 1.1, 0.1)
x, t

(tensor([-1.0000, -0.9000, -0.8000, -0.7000, -0.6000, -0.5000, -0.4000, -0.3000,
         -0.2000, -0.1000,  0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,
          0.6000,  0.7000,  0.8000,  0.9000,  1.0000]),
 tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
         0.9000, 1.0000]))

In [36]:
torch.stack(torch.meshgrid(x[0], t, indexing = 'xy')).reshape(2, -1).T

tensor([[-1.0000,  0.0000],
        [-1.0000,  0.1000],
        [-1.0000,  0.2000],
        [-1.0000,  0.3000],
        [-1.0000,  0.4000],
        [-1.0000,  0.5000],
        [-1.0000,  0.6000],
        [-1.0000,  0.7000],
        [-1.0000,  0.8000],
        [-1.0000,  0.9000],
        [-1.0000,  1.0000]])

In [30]:
bc1 = torch.stack(torch.meshgrid(x[0], t)).reshape(2, -1).T
bc2 = torch.stack(torch.meshgrid(x[-1], t)).reshape(2, -1).T
ic = torch.stack(torch.meshgrid(x, t[0])).reshape(2, -1).T # INtroducing variability into dataset?????????
torch.cat([bc1, bc2, ic])



tensor([[-1.0000,  0.0000],
        [-1.0000,  0.1000],
        [-1.0000,  0.2000],
        [-1.0000,  0.3000],
        [-1.0000,  0.4000],
        [-1.0000,  0.5000],
        [-1.0000,  0.6000],
        [-1.0000,  0.7000],
        [-1.0000,  0.8000],
        [-1.0000,  0.9000],
        [-1.0000,  1.0000],
        [ 1.0000,  0.0000],
        [ 1.0000,  0.1000],
        [ 1.0000,  0.2000],
        [ 1.0000,  0.3000],
        [ 1.0000,  0.4000],
        [ 1.0000,  0.5000],
        [ 1.0000,  0.6000],
        [ 1.0000,  0.7000],
        [ 1.0000,  0.8000],
        [ 1.0000,  0.9000],
        [ 1.0000,  1.0000],
        [-1.0000,  0.0000],
        [-0.9000,  0.0000],
        [-0.8000,  0.0000],
        [-0.7000,  0.0000],
        [-0.6000,  0.0000],
        [-0.5000,  0.0000],
        [-0.4000,  0.0000],
        [-0.3000,  0.0000],
        [-0.2000,  0.0000],
        [-0.1000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.1000,  0.0000],
        [ 0.2000,  0.0000],
        [ 0.3000,  0

In [32]:
ic[:, 0]

tensor([-1.0000, -0.9000, -0.8000, -0.7000, -0.6000, -0.5000, -0.4000, -0.3000,
        -0.2000, -0.1000,  0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,
         0.6000,  0.7000,  0.8000,  0.9000,  1.0000])